language: node_js
node_js:
  - "0.12.2"
before_install:
  - "npm install -g bower"
  - "bower install"
#  START FIREFOX
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#  START CHROMIUM
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
